"""Add clinic_id columns

Revision ID: 42a588f7eb18
Revises: c86661d3e7f4
Create Date: 2026-07-16 05:14:31.449109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a588f7eb18'
down_revision: Union[str, Sequence[str], None] = 'c86661d3e7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('clinic_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.add_column('patients', sa.Column('clinic_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.add_column('providers', sa.Column('clinic_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_providers_clinic_id'), 'providers', ['clinic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_clinic_id'), table_name='providers')
    op.drop_column('providers', 'clinic_id')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_column('patients', 'clinic_id')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_column('appointments', 'clinic_id')
    # ### end Alembic commands ###
